### ISSUE TITLE
Tutum CLI won't login on CircleCI - errors and stalls

### ISSUE THREAD

**Issue by KingScooty** [tutumcloud/cli#80]
This syntax should work:

```sh
tutum login -u [username] -p [password]
```

But for some reason it throws an error saying that it was only expecting one parameter. I've got environment variables set for TUTUM_USER and TUTUM_APIKEY also, but when trying to push to the tutum docker registry, it's still insisting on logging in with username and password via 2 steps. So the build just stalls.

So i'm struggling to push to the tutum docker registry from CircleCI at the moment. Really frustrating.

I installed tutum via `- sudo -H pip install tutum`

**Comment by fermayo** [comment]
As dicussed over slack, did you get any information back from Circle CI support?

**Comment by KingScooty** [comment]
I'm still waiting to hear back. I'll report back as soon as i hear something!

**Comment by jisikoff** [comment]
You don't need to the tutum CLI to push to tutum on circle, we have sucessfully automated this using a plain old docker login and docker push no problem.

**Comment by tifayuki** [comment]
@KingScooty 
As what @jisikoff  suggests, use `docker login`, `docker tag` and `push instead` of `tutum push`.
`tutum push` will probably be deprecated in the next version.

**Comment by KingScooty** [comment]
Well i'm not sure what i'm doing wrong now, but `docker login` followed by a `docker push` definitely doesn't seem to be working, i get prompted to login again. 

![img](https://s3.amazonaws.com/f.cl.ly/items/0C1h39320g2w0a1W3Q1Q/Screen%20Shot%202015-10-22%20at%2009.24.45.png)

**Comment by KingScooty** [comment]
Ah, it needs the `tutum.co` server parameter. For some reason i overlooked that every single time. Sorted now.
