### ISSUE TITLE
Impossible to loggin with API key

### ISSUE THREAD

**Issue by Ducatel** [tutumcloud/cli#81]
Hi everybody,

## Problem explanation
 
I'm trying to login my tutum client with my API key. [(like explain in the documentation)](https://docs.tutum.co/v2/api/?shell#rest-api)

When I execute my command,  I always have the same error (with my api key, my account password, my email)

```
root@serveur-2:~# tutum login -u MY_USERNAME -p MY_API_KEY
Email:
Wrong username and/or password. Please try to login again
root@serveur-2:~# tutum login -u MY_USERNAME -p MY_API_KEY
Email: MY@EMAIL.fr
Wrong username and/or password. Please try to login again
```

But it's working with curl
```
curl -H "Authorization: ApiKey MY_USERNAME:MY_API_KEY" https://dashboard.tutum.co/api/v1/service/
 
> Code 200
> {"meta": {"limit": 25, "next": null, "offset": 0, "previous": null, "total_count": 0}, "objects": []}
```

## System info
 
* OS: Ubuntu 14.04.1 LTS 
* Tutum cli version: 0.16.21
* Python 2.7.6

## Questions

So do you know how I can log me in with my API key ?
I did somethings wrong ?
Why the client ask me my email ?

Thanks in advance for your help

**Comment by tifayuki** [comment]
`tutum login` accepts username and password

If you want to use APIKEY, you can do:
1) use environment variable 
```
export TUTUM_USER=username
export TUTUM_APIKEY=apikey
```
or 2) create ~/.tutum file, with the content:
```
[auth]
user = "username"
apikey = "apikey"
``` 
More detailed information are in README:https://github.com/tutumcloud/cli#authentication

**Comment by Ducatel** [comment]
Ok thanks ;)
I think this should be in the documentation
https://support.tutum.co/support/solutions/articles/5000513678-bring-your-own-node
