### ISSUE TITLE
Not able to login to tutum using tutum cli command as mentioned in documentation

### ISSUE THREAD

**Issue by sgollamudi** [tutumcloud/cli#83]
tutum login 
does not work. gives me wrong username/password. Please try again.
using docker to run, also does not work. 

    bash-3.2$ docker run -it -e TUTUM_USER=username -e TUTUM_APIKEY=apikey tutum/cli
    usage: tutum [-h] [-v]
                 {action,build,container,event,exec,image,login,node,nodecluster,push,run,service,stack,tag,volume,volumegroup,trigger,up}
             ...

    Tutum's CLI

    optional arguments:
      -h, --help            show this help message and exit
      -v, --version         show program's version number and exit

**Comment by tifayuki** [comment]
The document is wrong, cannot use apikey as password.
Will fix the doc as ASAP.
If you want to use apikey, see:
https://github.com/tutumcloud/cli/issues/81

**Comment by sgollamudi** [comment]
Can you please tell me how to login then? I tried: 
    tutum login
prompts for username
   username: MY_USERNAME
   password: MY_PWD
   email: MY_EMAIL@ABC.com
   Wrong username and/or password. Please try to login again

**Comment by tifayuki** [comment]
use password of tutum.
if you registered you account with docker hub, github, etc. you have to go to our website, and setup a password first.
