### ISSUE TITLE
Outdated version v0.16.21 on brew (for Mac)

### ISSUE THREAD

**Issue by mobidev111** [tutumcloud/cli#86]
```
brew install tutum
```
only delivers the outdated version v0.16.21

please update

**Comment by tifayuki** [comment]
Did you do `brew update` before `brew install tutum`?
The latest version of cli on brew is `0.20.2`

**Comment by mobidev111** [comment]
Yep, works now. Don't use brew very often. Maybe worth a mention on README.md for casual users.
```sh
brew update && brew uninstall tutum && brew install tutum
```
