### ISSUE TITLE
Cant auth via ENV vars when using cli from dockerhub

### ISSUE THREAD

**Issue by kubenstein** [tutumcloud/cli#90]
when i try to execute cli commands using docker image, im asked to authorise even proper envs are set:
```
docker run -it --rm -e TUTUM_USER=username -e TUTUM_APIKEY=apikey  tutum/cli ...
Not Authorized, Please login:
```
i noticed that this issue is solved in more up to date version of tutum cli. The one from dockerhub is `tutum 0.16.0.1`

If i build image myself, all is working. 
So i guess its a matter of updating dockerhub repo

**Comment by tifayuki** [comment]
@kubenstein 
 For some reason, the auto build of the image is not triggered on dockerhub. I have built the image. Can you give a try?

**Comment by kubenstein** [comment]
All is working now. thank you for quick response.
