### ISSUE TITLE
Not possible to login with brew installed tutum

### ISSUE THREAD

**Issue by Snorlock** [tutumcloud/cli#91]
Hi I just installed tutum through brew but it does not  have any sucessful feedback messages.

When typing login, i enter right password and username but I dont get any message about successful or unsuccessful. When I try to list nodes I get unathorized but  its tsuck in this loop until i CTRL c out of it.
I uninstalled the tutum from brew and used pip instead.

The pip version worked, gave proper message feedback on login and I can use the commands.

My mac version is 10.10.5.

If there is anyhwere I should start debugging, let me know please.

**Comment by tifayuki** [comment]
Maybe related to this issue 
https://github.com/tutumcloud/cli/issues/86

**Comment by Snorlock** [comment]
Thx, seems to be the issue yes!
